# Generated by Django 5.2.7 on 2026-02-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilebackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_question',
            field=models.CharField(blank=True, choices=[('mother_maiden', "What is your mother's maiden name?"), ('first_pet', 'What was the name of your first pet?'), ('first_school', 'What was the name of your first school?'), ('birth_city', 'In what city were you born?'), ('favorite_book', 'What is your favorite book?')], max_length=50, null=True),
        ),
    ]
